[package]
name = "masssnd"
version = "0.0.1"
authors = ["nxnjz <nxnjz@nxnjz.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap ="2.33"
cidr="0.1"
crossbeam="0.7"
